# here is the algorithm, generated by ChatGPT, of maintaining the maximum value in
# a sliding window with total of linear time. recall that in the past I always
# use the combination of priority queue and hash map to do the same thing, which take
# n*log(n) time. this is the solution which provide O(n) time comp


# the idea here is to use a deque and make it also monotonic decreasing, and the deque, at
# any given moment, only contains the candidates of the maximum value in the window
def sliding_window_max(nums, k):
    dq = deque()
    result = []

    for i in range(len(nums)):
        # Remove indices out of the window
        while dq and dq[0] <= i - k:
            dq.popleft()

        # Remove smaller values from back
        while dq and nums[dq[-1]] < nums[i]:
            dq.pop()

        dq.append(i)

        # Append max to result once we have a full window
        if i >= k - 1:
            result.append(nums[dq[0]])

    return result
